version: '3'

services:
  redis:
    image: redis:7.2-rc2-alpine
    ports:
      - 6379:6379
  
  backend:
    build:
      context: ./backend/
      dockerfile: dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  
  #frontend:    
    #build: