FROM python:3.11.3-alpine3.17

WORKDIR /backend

RUN apk update && pip install --upgrade pip

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

COPY ./RedisListener.py ./

CMD ["python3.11","RedisListener.py"]